version: '3.4'
services:
  game:
    image: "ghcr.io/gameservermanagers/linuxgsm-docker:latest"
    environment:
      - GAMESERVER=pzserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /mnt/e/zomboid/wsl/serverfiles:/home/linuxgsm/serverfiles
      - /mnt/e/zomboid/wsl/log:/home/linuxgsm/log
      - /mnt/e/zomboid/wsl/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"

  web:
    image: dcr.thefipster.com/zomboid/zamboni
    build:
      context: webapp
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DATABASE_PATH: "/var/zamboni"
      ZOMBOID_PATH: "/var/zamboni/config"
      DOCKER_SOCKET: "npipe://./pipe/docker_engine"
    volumes:
      - /mnt/e/zomboid/server/server-control-test:/var/zamboni
    ports:
      - "8888:80"
    